name = "ClosedIntervals"
uuid = "059b0e18-018a-5deb-a5b2-c624ee85784b"
version = "0.3.0"
[deps]
AbstractLattices = "398f06c4-4d28-53ec-89ca-5b2656b7603d"

[compat]
julia = "1"
AbstractLattices = "0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
